### ISSUE TITLE
Rate limit for Github API calls

### ISSUE THREAD

**Issue by Megh-Thakkar** [biojs/biojs-backend#15]
After registering the app on Github, the github api allows only 5000 calls per hour([link](https://developer.github.com/v3/#rate-limiting)). Hence, keeping in mind the number of calls for each component to Github and an approximate increase in the number of components in the near future, the cronjob for updating the components would be running every 15 minutes. This can be decreased if we can find a way to increase the number of allowed calls, which can be looked into in the near future.

**Comment by DennisSchwartz** [comment]
We need to keep this in mind, but it's not a problem we currently face. I'll close it for now, feel free to re-open if we hit the rate limit.
