### ISSUE TITLE
Some visualizations have their own HTML files

### ISSUE THREAD

**Issue by sarthak-sehgal** [biojs/biojs-backend#35]
The visualizations of the component "bio-pv" have their own HTML files with a custom "div" and thus there visualizations are not loading in the new website. See: http://139.59.93.32/biojs-frontend/dist/#/component/bio-pv
Old website: http://biojs.io/d/bio-pv
GitHub repo snippets' folder: https://github.com/biasmv/pv/tree/master/snippets

**Comment by DennisSchwartz** [comment]
Closing this in favour of a more comprehensive re-work of visualisations
