### ISSUE TITLE
Changeover DNS to point to new website

### ISSUE THREAD

**Issue by rowlandm** [biojs/biojs-backend#39]
But also have a way of going back to the old website too.

**Comment by Megh-Thakkar** [comment]
As I mentioned [here](https://github.com/biojs/biojs-backend/issues/40), if we need to keep the current registry running, we can set it under a sub-domain with biojs.io, such as original.biojs.io, whatever sounds perfect. This way, if it is extremely urgent, we can redirect biojs.io to it and hence, can go back in a matter of minutes.

@rowlandm @DennisSchwartz @yochannah

**Comment by rowlandm** [comment]
we have biojs.net and biojs.io

what about keeping biojs.io as it is currently, making biojs.net the new
website.

The blog could then be hosted under blog.biojs.net?

What do you think Dennis and Yo?

**Comment by yochannah** [comment]
I think that sounds perfect @rowlandm - but also perhaps place a banner on .io suggesting to users that they should visit .net to try out our new site?

**Comment by rowlandm** [comment]
Yep

**Comment by Megh-Thakkar** [comment]
Sounds great!

**Comment by DennisSchwartz** [comment]
Done
