### ISSUE TITLE
How do we handle the github.io vs biojs.io vs new website

### ISSUE THREAD

**Issue by rowlandm** [biojs/biojs-backend#40]

**Comment by Megh-Thakkar** [comment]
I would suggest that we set up sub-domains, for the current biojs.io repository (<something>/biojs.io) and blog.biojs.io for the blogs. The latter can be done quickly as we only to point blog.biojs.io to biojs.github.io.
Also, if we do not plan to publish general blog posts anytime soon, we can publish the blog as **gsoc.biojs.io**. This would be helpful for future aspirants to understand the website project better and hence, would improve further collaboration. A tab for information of BioJS as well as OBF specifically regarding GSoC can be added for the same.

**Comment by DennisSchwartz** [comment]
That's a very good idea @Megh-Thakkar! I will send you the credentials to Cloudflare on gitter.

**Comment by yochannah** [comment]
I'd like to keep the option of having a blog that's non-gsoc related. I'd been thinking of inviting [these folks](https://twitter.com/BiojsLibrary/status/1012045314318974976) over for an interview, plus we probably want a "new site launch" blog. and it's just occurred to me we should have a biohackathon blog too. I'm not sure when I'll have time for these :laughing:

**Comment by rowlandm** [comment]
Can we make the gsoc blog a generic blog?

**Comment by yochannah** [comment]
I think that would be a good idea! So blog.biojs.net might be better than
gsoc.biojs.net ;)

**Comment by rowlandm** [comment]
Yep

**Comment by Megh-Thakkar** [comment]
Sounds great @all!

**Comment by DennisSchwartz** [comment]
I think this is resolved :)
